language: node_js
node_js:
- '6'
notifications:
  slack:
    secure: j8b1NT8uuBWn6EjQmCR2Wrt9l68d1JT6iymGAduivxLruHwqWSwbUzjHsqCN9/7M6H+yGeRNZmsKwgKqltQxxjhid6dv1wwsDvArXJuxyNm7M59Yjl/8biZqAK1BDgLfeWWfdqotuQRO1372q2l6WySbYDxH/GN/cThLZsGoK1o+ZIWmOLO1FRkpUvUYRQpQIEG7iS68dVwEZIlxTRUL6ZgdMpXXznIOxyyZg89j7RZEPqjiXd7gVVTWRFpvG09FWIN9ngmXBQKju7YKeS7RUs/lKNlfvTfhA+Pb6h0p0Z+vGGcUvbMapLMWtXuR+BGNQFZ7EcdQhf/fNFtHGqrOBSHEdGDGd3uiDXK1Xr2sHkGHggRaf9pGFbtIHsRAmcGl60o3a/1giJkDcI6PLOG8lx2Zm4hbjtu9febNlWt5t/eOreTQH2irJBAPU30VaFafG3s0GmVxzoSG39Lp9E7ffzuzlXiBvVDl+q41SMO44RJhNWl/GXlkjvXKhP9qgxjDy7V11u4LxbOc17A3YVd3GeN4JPqOsR6wSc8ArQ8NCTwfvAbJ45afq1Siw9Rpn0FYxzTQm3w6GrTXeZrZGYNv2Y3n3Tuklmkok4u3FPXZXYl9n6KDgQjpGwV9MtRPIAytkIFwwCIfVzUVg8DBtnvmu8kn3HJjVmXugl3hFtvXfqI=
